kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "swim-vacancy-alarm.fullname" . }}
  labels:
    {{- include "swim-vacancy-alarm.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}

